const domande = {
    1: [
        { domanda: "Cosa è il carbone?", risposta: "È un combustibile fossile." },
        { domanda: "Da cosa deriva il carbone?", risposta: "Dalla lenta e graduata decomposizione del legno di antiche foreste." },
        { domanda: "Da cosa è formata le cellulosa?", risposta: "Da carbonio, idrogeno e ossigeno." },
        { domanda: "Quali sono i carboni fossili?", risposta: "Torba, lignite, litantrace, antracite." },
        { domanda: "La torba è un combustibile fossile?", risposta: "No, perché non è ancora ben sviluppato." },
        { domanda: "Cosa è la lignite?", risposta: "È il carbone fossile più giovane." },
        { domanda: "Cosa è la litantrace?", risposta: "È il carbone fossile più utilizzato." },
        { domanda: "Cosa è la antracite?", risposta: "È il carbone fossile più antico." },
        { domanda: "Quali sono i metodi di estrazione del carbone?", risposta: "A cielo aperto e in sotterranea." },
        { domanda: "Quale non è un carbone fossile?", risposta: "Torba." },
        { domanda: "La litantrace è detta hard coal?", risposta: "Sì." },
        { domanda: "Nella miniera a cielo aperto vengono o no sradicati dei terreni?", risposta: "Sì che vengono sradicati." },
        { domanda: "La lignite è detto hard coal?", risposta: "No." },
        { domanda: "Il carbone si forma sotto azione di grandi pressioni ?", risposta: "Sì." },
        { domanda: "Il carbone si forma con basse temperature?", risposta: "No." },
        { domanda: "Per cosa viene usato il carbone?", risposta: "Per produrre energia, per la siderurgia, per la industria chimica, per il riscaldamento e per la cottura dei cibi." },
        { domanda: "Il carbone è usato per il riscaldamento?", risposta: "Sì." },
        { domanda: "La antracite ha il più basso potere calorifico?", risposta: "No." },
        { domanda: "Nella era primaria gran parte della terra è occupata da foreste acquitrinose?", risposta: "Sì." },
        { domanda: "Cosa succede nella era terziaria?", risposta: "Il carbone torna in superficie per i rivolgimenti della crosta terrestre." },
        { domanda: "Nelle miniere in sotterranea si crea un pozzo con gallerie orizzontali?", risposta: "Sì." },
        { domanda: "Come si chiama il gas senza colore e senza sapore nelle miniere?", risposta: "Grisou." },
        { domanda: "Nella era secondaria non si trovano i rivolgimenti della crosta terrestre?", risposta: "No." },
        { domanda: "La lignite ha usi chimici?", risposta: "No." },
        { domanda: "Nelle miniere a cielo aperto si usano macchine scavatrici?", risposta: "Sì." }
    ],
    2: [
        
        { domanda: "Che cosa è il petrolio?", risposta: "È un liquido oleoso" },
        { domanda: "Di che colore è il petrolio?", risposta: "È di colore bruno, tendente al nero" },
        { domanda: "Il petrolio ha massa volume maggiore o inferiore della acqua?", risposta: "Ha massa volumica inferiore dell'acqua quindi può galleggiare" },            { domanda: "Cosa sono gli idrocarburi?", risposta: "Sono dei composti chimici formati da idrogeno e carbonio" },
        { domanda: "Fai un esempio di idrocarburi gassosi", risposta: "Il metano" },
        { domanda: "Dove resta il petrolio nella sua creazione quando, l ultimo strato è impermeabile?", risposta: "Nella roccia magazzino" },
        { domanda: "Perché nella ricerca petrolifera il primo passaggio è quello cercare delle rocce sedimentarie?", risposta: "Perché possono contenere idrocarburi" },
        { domanda: "Con cosa avviene la ricerca di un giacimento trappola?", risposta: "Con il pozzo esplorativo" },
        { domanda: "Cos'è il derrick?", risposta: "L'elemento principale per estrarre il petrolio dal sottosuolo" },
        { domanda: "A cosa serve la pompa di estrazione?", risposta: "Serve quando gli idrocarburi non hanno pressione sufficiente per risalire in superficie" },
        { domanda: "Con cosa avviene la regolazione del flusso?", risposta: "Con un complesso di valvole detto 'albero di natale'" },
        { domanda: "Cosa avviene nella sedimentazione?", risposta: "Avviene la separazione di fanghi e frammenti di roccia in serbatoi di sedimentazione" },
        { domanda: "Cosa avviene nella ricerca offshore?", risposta: "La perforazione dei fondali marini con grandi piattaforme metalliche" },
        { domanda: "Quali sono i 2 modi per trasportare il petrolio in raffineria?", risposta: "Con l'oleodotto o con la nave petroliera" },
        { domanda: "Come scorre il petrolio all interno degli oleodotti?", risposta: "Viene spinto all’interno da stazioni di pompaggio" },
        { domanda: "Cosa è la raffineria?", risposta: "È lì dove avviene la raffinazione" },
        { domanda: "Cosa è la raffinazione?", risposta: "È un processo di separazione dei vari componenti degli idrocarburi" },
        { domanda: "Fai 1 esempio di impieghi del petrolio.", risposta: "Combustibile per centrali elettriche" },
        { domanda: "Qual'è il paese che produce più petrolio?", risposta: "Gli Stati Uniti" },
        { domanda: "Quale è il paese che produce meno petrolio?", risposta: "L'Africa in generale" },
        { domanda: "Il petrolio causa danni all ambiente?", risposta: "No" },
        { domanda: "L Italia è uno tra i maggior produttori di petrolio?", risposta: "No" },
        { domanda: "Quali danni ambientali causa il petrolio nell'acqua?", risposta: "Esplosioni di impianti offshore, incidenti tra le navi e lavaggio illegale tra le cisterne" },
        { domanda: "Quali danni ambientali causa il petrolio nell'atmosfera?", risposta: "Gas di scarico da veicoli e fumi da centrali termoelettriche" },
        { domanda: "Quali danni ambientali causa il petrolio alla Terra?", risposta: "Incidenti nel trasporto via terra e lo smaltimento fanghi di perforazione" },
        { domanda: "Che cos'è una centrale a turbogas?", risposta: "È una centrale termoelettrica che produce energia elettrica sfruttando un ciclo basato sulla combustione di gas e l’espansione dei gas combusti in una turbina." },
        { domanda: "Qual è il principio di funzionamento di una centrale a turbogas?", risposta: "Il combustibile (gas naturale o gasolio) viene bruciato in una camera di combustione, producendo gas ad alta temperatura che fanno girare una turbina collegata a un generatore elettrico." },
        { domanda: "Quali sono i componenti principali di una centrale a turbogas?", risposta: "Compressore, camera di combustione, turbina a gas e generatore elettrico." },
        { domanda: "Che tipo di combustibile viene utilizzato in una centrale a turbogas?", risposta: "Principalmente gas naturale, ma può essere usato anche gasolio o biogas." },
        { domanda: "Come avviene la combustione nella centrale?", risposta: "L aria compressa viene miscelata con il combustibile nella camera di combustione e incendiata, generando gas ad alta temperatura e pressione." },
        { domanda: "Che ruolo ha il compressore nella centrale a turbogas?", risposta: "Comprime l'aria necessaria per la combustione, aumentando l'efficienza del processo." },
        { domanda: "Come si genera il movimento della turbina?", risposta: "I gas caldi in espansione spingono le pale della turbina, facendola girare." },
        { domanda: "Come viene prodotta l energia elettrica nella centrale?", risposta: "La turbina è collegata a un generatore che converte l'energia meccanica in energia elettrica." },
        { domanda: "Qual è la funzione del generatore elettrico?", risposta: "Trasforma l energia meccanica della turbina in energia elettrica utilizzabile." },
        { domanda: "Cosa succede ai gas di scarico dopo aver attraversato la turbina?", risposta: "Vengono rilasciati nell atmosfera o recuperati in impianti a ciclo combinato per produrre ulteriore energia." },
        { domanda: "Perché le centrali a turbogas sono spesso abbinate a impianti a ciclo combinato?", risposta: "Per recuperare il calore dei gas di scarico e aumentare l efficienza complessiva del sistema." },
        { domanda: "Quali sono i vantaggi di una centrale a turbogas rispetto ad altre centrali termoelettriche?", risposta: "Rapidità di avvio, minori emissioni di CO₂ rispetto al carbone e dimensioni ridotte." },
        { domanda: "Quali sono gli svantaggi delle centrali a turbogas?", risposta: "Costo elevato del combustibile e minore efficienza rispetto alle centrali a ciclo combinato." },
        { domanda: "Qual è l'efficienza di una centrale a turbogas?", risposta: "Generalmente tra il 30% e il 40%, ma può aumentare in un ciclo combinato." },
        { domanda: "Come si può migliorare l efficienza di una centrale a turbogas?", risposta: "Utilizzando il calore residuo per produrre vapore e azionare una turbina a vapore (ciclo combinato)." },
        { domanda: "Qual è il tempo di avvio di una centrale a turbogas?", risposta: "Molto rapido, generalmente pochi minuti." },
        { domanda: "Perché le centrali a turbogas sono utilizzate per coprire i picchi di domanda energetica?", risposta: "Perché possono essere attivate rapidamente quando necessario." },
        { domanda: "Quali sono le emissioni inquinanti di una centrale a turbogas?", risposta: "Anidride carbonica (CO₂), ossidi di azoto (NOx) e piccole quantità di particolato." },
        { domanda: "Come si possono ridurre le emissioni delle centrali a turbogas?", risposta: "Utilizzando tecnologie di filtrazione, combustibili più puliti e sistemi di riduzione delle emissioni NOx." },
        { domanda: "Quali sono gli utilizzi principali di una centrale a turbogas?", risposta: "Produzione di energia elettrica per la rete e generazione di energia in impianti industriali." },
        { domanda: "Quali sono i principali paesi che utilizzano centrali a turbogas?", risposta: "Stati Uniti, Germania, Italia, Giappone e Arabia Saudita." },
        { domanda: "Come si confronta una centrale a turbogas con una a carbone in termini di impatto ambientale?", risposta: "Le centrali a turbogas emettono meno CO₂ e inquinanti rispetto a quelle a carbone." },
        { domanda: "Che ruolo hanno le energie rinnovabili nel ridurre la dipendenza dalle centrali a turbogas?", risposta: "Possono sostituire gradualmente l energia prodotta dal gas, riducendo le emissioni di CO₂." },
        { domanda: "Come potrebbe evolvere la tecnologia delle centrali a turbogas in futuro?", risposta: "Maggiore efficienza, uso di idrogeno come combustibile e sistemi di cattura della CO₂." },
        { domanda: "Quali sono le alternative più sostenibili alle centrali a turbogas?", risposta: "Energia solare, eolica, idroelettrica e nucleare." }
        ],
        
    3: [
        { domanda: "Quale è l altro nome che viene usato per indicare il gas naturale?", risposta: "Il metano" },
        { domanda: "Il gas naturale è il più sporco o il più pulito tra i combustibili fossili?", risposta: "Il più pulito" },
        { domanda: "Come si forma?", risposta: "Per lenta decomposizione di sostanze organiche durante milioni di anni" },
        { domanda: "Dove si può trovare il metano in maggior quantità?", risposta: "Nelle regioni petrolifere" },
        { domanda: "Il gas naturale si può trovare anche in zone povere o prive di petrolio?", risposta: "Si" },
        { domanda: "Perchè il gas naturale si può trovare anche in zone prive/povere di petrolio?", risposta: "Perchè i gas tendono a spostarsi nel sottosuolo con maggiore facilità dei liquidi." },
        { domanda: "Con cosa viene trasportato il metano?", risposta: "Con i gasdotti o metanodotti" },
        { domanda: "Per cosa viene utilizzato il metano?", risposta: "Per produrre energia elettrica" },
        { domanda: "Al posto di che cosa viene utilizzato il metano nelle centrali elettriche?", risposta: "Al posto del carbone" },
        { domanda: "Il metano è utilizzato per produrre energia termica?", risposta: "Si" },
        { domanda: "Il metano è utilizzato anche negli usi domestici e civili?", risposta: "Si" },
        { domanda: "Fai un esempio dove il metano viene utilizzato per usi domestici", risposta: "Cucine a gas, riscaldamento" },
        { domanda: "Il metano è utilizzato nella industria chimica?", risposta: "Si" },
        { domanda: "Il gas naturale è più economico rispetto al carbone o al petrolio per la produzione di energia?", risposta: "Sì, poiché ha un potere calorifico maggiore e una minore necessità di costosi impianti di trattamento." },
        { domanda: "Quali sono i principali paesi produttori di gas naturale?", risposta: "Stati Uniti, Russia, Canada e diversi paesi Arabi." },
        { domanda: "Come viene estratto il gas naturale dal sottosuolo?", risposta: "Il gas naturale viene estratto tramite perforazioni nel terreno o nel mare, utilizzando tecniche come la trivellazione diretta in caso di riserve non convenzionali." },
        { domanda: "Qual è la principale fonte di inquinamento legata all estrazione di gas naturale?", risposta: "La principale fonte di inquinamento è il rilascio di metano, durante la estrazione e il trasporto." },
        { domanda: "Il gas naturale può essere utilizzato come carburante per veicoli?", risposta: "Sì, il gas naturale può essere utilizzato come carburante per veicoli." },
        { domanda: "Quali sono i principali vantaggi nell utilizzo del gas naturale rispetto ad altri combustibili fossili?", risposta: "Il gas naturale emette meno CO₂ e inquinanti rispetto al carbone e al petrolio, ed è più efficiente nella produzione di energia elettrica e termica." },
        { domanda: "In che modo l uso del gas naturale influisce sulle emissioni di gas serra?", risposta: "L uso del gas naturale riduce le emissioni di CO₂ rispetto ad altri combustibili fossili, ma, se rilasciato in modo incontrollato, è un gas serra molto più potente del CO₂." },
        { domanda: "Che cos'è una centrale termoelettrica?", risposta: "Una centrale termoelettrica è un impianto che trasforma l'energia termica prodotta dalla combustione di combustibili fossili in energia elettrica." },
        { domanda: "Quale combustibile viene utilizzato nelle centrali termoelettriche?", risposta: "Possono essere utilizzati carbone, gas naturale, petrolio o biomasse." },
        { domanda: "Come viene prodotto il calore all'interno della centrale?", risposta: "Il calore viene prodotto bruciando il combustibile in una caldaia per riscaldare l'acqua e trasformarla in vapore ad alta pressione." },
        { domanda: "A cosa serve il calore prodotto nella centrale?", risposta: "Il calore serve a generare vapore che fa girare una turbina collegata a un generatore elettrico." },
        { domanda: "Che cosa si intende per turbina a vapore?", risposta: "È un macchinario che trasforma l'energia del vapore in movimento rotatorio." },
        { domanda: "In che modo l'energia meccanica viene trasformata in energia elettrica?", risposta: "La turbina, girando, mette in movimento il rotore del generatore, creando corrente elettrica." },
        { domanda: "Quali sono le principali parti di una centrale termoelettrica?", risposta: "Le principali parti sono la caldaia, la turbina a vapore, il generatore elettrico e il sistema di raffreddamento." },
        { domanda: "Perché le centrali termoelettriche sono spesso costruite vicino a fonti d'acqua?", risposta: "Perché l'acqua è necessaria per il raffreddamento del vapore e per il ciclo di produzione dell'energia." },
        { domanda: "Come viene raffreddato il vapore dopo aver fatto girare la turbina?", risposta: "Il vapore viene raffreddato attraverso un condensatore, dove torna allo stato liquido per essere riutilizzato." },
        { domanda: "Qual è la funzione della caldaia in una centrale termoelettrica?", risposta: "La caldaia serve a riscaldare l'acqua e trasformarla in vapore ad alta pressione." },
        { domanda: "Quali sono gli effetti ambientali della produzione di energia in una centrale termoelettrica?", risposta: "Le centrali termoelettriche emettono gas serra, inquinano l'aria e contribuiscono al cambiamento climatico." },
        { domanda: "Che cos'è l'effetto serra e come è legato alle centrali termoelettriche?", risposta: "L'effetto serra è il fenomeno per cui alcuni gas trattengono il calore sulla Terra; le centrali termoelettriche contribuiscono con l emissione di CO₂." },
        { domanda: "Come si possono ridurre le emissioni di gas inquinanti dalle centrali termoelettriche?", risposta: "Con l'uso di filtri, tecnologie di cattura della CO₂ e passando a combustibili meno inquinanti." },
        { domanda: "Quali sono i vantaggi delle centrali termoelettriche?", risposta: "Producono energia in modo continuo e sono tecnologicamente avanzate." },
        { domanda: "Quali sono gli svantaggi delle centrali termoelettriche?", risposta: "Inquinano, consumano molte risorse naturali e dipendono dai combustibili fossili." },
        { domanda: "Quali sono le differenze tra una centrale termoelettrica a carbone e una a gas naturale?", risposta: "Quelle a carbone inquinano di più, mentre quelle a gas naturale producono meno CO₂ e sono più efficienti." },
        { domanda: "Perché l'energia prodotta dalle centrali termoelettriche non è considerata rinnovabile?", risposta: "Perché utilizza combustibili fossili, che si esauriscono e non si rigenerano rapidamente." },
        { domanda: "Perché le centrali termoelettriche hanno bisogno di sistemi di filtraggio per i gas di scarico?", risposta: "Per ridurre l inquinamento atmosferico causato dalla combustione dei combustibili fossili." },
        { domanda: "Qual è il ruolo delle ciminiere nelle centrali termoelettriche?", risposta: "Servono a disperdere i gas di scarico in atmosfera per ridurre l'inquinamento locale." },
        { domanda: "In quali settori viene utilizzata l'energia prodotta dalle centrali termoelettriche?", risposta: "Nell'industria, nei trasporti, negli edifici e nei servizi pubblici." }
    ]
    ,
    4: [
        { domanda: "Che cosa è l'energia nucleare?", risposta: "È una forma di energia che deriva da profonde modificazioni della struttura della materia." },
        { domanda: "Chi era Albert Einstein?", risposta: "Era un fisico matematico e scienziato" },
        { domanda: "Che cosa ha scoperto Albert Einstein?", risposta: "Ha scoperto che la materia si può trasformare in energia." },
        { domanda: "Quale formula utilizzo Einstein per capire quanta energia si può produrre?", risposta: "E=MC²." },
        { domanda: "quali sono i processi che possono produrre energia nucleare?", risposta: "Fissione e fusione nucleare." },
        { domanda: "In che cosa consiste la fissione nucleare?", risposta: "La fissione consiste nella disintegrazione del nucleo dell'atomo di un elemento fissile. Per mezzo di neutroni che colpiscono questo elemento, lo spezzano e si formano 2 nuclei più leggeri. Durante il processo, una parte di materia si è trasformata in energia." },
        { domanda: "Qual è l altro termine che viene utilizzato come sinonimo di fissioneScissione nucleare?", risposta: "Scissione nucleare." },
        { domanda: "Che cosa è l elemento fissile?", risposta: "L'elemento fissile è quell'elemento indispensabile per far avvenire la fissione." },
        { domanda: "Qual è l elemento fissile utilizzato durante la fissione?", risposta: "Uranio 235." },
        { domanda: "Qual È quel materiale che si ottiene durante la fissione?", risposta: "Plutonio." },
        { domanda: "Il plutonio è disponibile in natura?", risposta: "No." },
        { domanda: "L Uranio 235 in percentuale quanto è disponibile in natura?", risposta: "7 per mille" },
        { domanda: "Qual è il simbolo dell Uranio?", risposta: "U (uranium)." },
        { domanda: "Come funzionano le centrali nucleari?",  risposta: "Il calore prodotto dalla fissione serve a generare vapore surriscaldato che mette in rotazione la turbina a vapore, la quale è collegata all'alternatore che produce energia elettrica." },
        { domanda: "Come si chiamano i 2 atomi che si formano durante la fissione?", risposta: "Crypton e barion." },
        { domanda: "Cosa è successo nel 1986 ?", risposta: "Esplosione della centrale nucleare di Chernobyl." },
        { domanda: "Cosa avvenne a causa del disastro di Cernoby?", risposta: "Morti, malformazioni e distruzione nelle aree limitrofe." },
        { domanda: "La esplosione è avvenuta per errore umano?", risposta: "Sì." },
        { domanda: "Cosa scatenò il disastro di Fukushima?", risposta: "Un terremoto che generò un enorme tsunami." },
        { domanda: "Come viene utilizzato l uranio nella 2ª guerra mondiale?", risposta: "Per produrre bombe nucleari." },
        { domanda: "In che cosa consiste la fusione ?", risposta: "Consiste nell'unione di 2 atomi di idrogeno per formare un altro atomo più grande." },
        { domanda: "Durante la fusione cosa si crea?", risposta: "Elio." },
        { domanda: "Viene utilizzata di più la fusione o la fissione?", risposta: "La fissione." },
        { domanda: "In Italia ci sono centrali nucleari aperte?", risposta: "No." },
        { domanda: "Che cos'è una centrale elettronucleare ad acqua bollente?", risposta: "È un impianto che produce energia elettrica sfruttando il calore generato dalla fissione nucleare per far bollire l'acqua e creare vapore." },
        { domanda: "Che tipo di reattore viene utilizzato in questo tipo di centrale?", risposta: "Un reattore nucleare ad acqua bollente." },
        { domanda: "Qual è il principio di funzionamento di una centrale elettronucleare ad acqua bollente?", risposta: "Il calore prodotto dalla fissione nucleare viene usato per far bollire direttamente l'acqua del reattore, producendo vapore che aziona una turbina collegata a un generatore elettrico." },
        { domanda: "Qual è la differenza principale tra una centrale elettronucleare ad acqua bollente e una ad acqua pressurizzata?", risposta: "Nel reattore ad acqua bollente, il vapore che aziona la turbina proviene direttamente dal reattore, mentre in quello ad acqua pressurizzata il vapore è prodotto in un generatore di vapore separato." },
        { domanda: "Quale combustibile nucleare viene usato nella centrale elettronucleare ad acqua bollente?", risposta: "Generalmente viene utilizzato l'uranio arricchito." },
        { domanda: "Dove avviene la fissione nucleare nella centrale?", risposta: "All'interno del nocciolo del reattore, dove si trovano le barre di combustibile." },
        { domanda: "Come viene generato il vapore per azionare la turbina?", risposta: "Il calore prodotto dalla fissione nucleare fa bollire direttamente l'acqua all'interno del reattore." },
        { domanda: "Perché il vapore generato è radioattivo?", risposta: "Perché passa direttamente attraverso il reattore e può entrare in contatto con materiali radioattivi." },
        { domanda: "Che funzione ha la turbina nella centrale?", risposta: "Trasforma l'energia del vapore in energia meccanica, che viene poi convertita in elettricità dal generatore." },            
        { domanda: "Come si trasforma il vapore in energia elettrica?", risposta: "Il vapore fa girare la turbina, che a sua volta aziona un generatore elettrico per produrre corrente." },
        { domanda: "Cosa succede al vapore dopo aver azionato la turbina?", risposta: "Viene raffreddato e trasformato nuovamente in acqua per essere riutilizzato." },
        { domanda: "Qual è il ruolo del condensatore nella centrale elettronucleare ad acqua bollente?", risposta: "Raffredda il vapore esausto della turbina, trasformandolo in acqua liquida." },
        { domanda: "Come viene raffreddato il vapore dopo l'uso nella turbina?", risposta: "Passa attraverso uno scambiatore di calore chiamato condensatore, dove viene raffreddato con acqua prelevata da fiumi, laghi o torri di raffreddamento." },
        { domanda: "Che ruolo ha l acqua di raffreddamento nella centrale?", risposta: "Serve a mantenere la temperatura del reattore sotto controllo e a condensare il vapore esausto." },
        { domanda: "Quali sono i principali sistemi di sicurezza di una centrale elettronucleare ad acqua bollente?", risposta: "Sistemi di emergenza per il raffreddamento, barriere di contenimento per evitare fuoriuscite radioattive e sistemi di arresto automatico del reattore." },
        { domanda: "Come si evita il surriscaldamento del reattore?", risposta: "Con sistemi di raffreddamento continui e barre di controllo che regolano la reazione nucleare." },
        { domanda: "Perché il combustibile nucleare deve essere sostituito periodicamente?", risposta: "Perché l'uranio si consuma gradualmente e perde la capacità di sostenere la fissione." },
        { domanda: "Cosa succede alle scorie nucleari prodotte dalla centrale?", risposta: "Vengono immagazzinate in depositi sicuri per evitare contaminazioni radioattive." },
        { domanda: "Quali sono i vantaggi di una centrale elettronucleare ad acqua bollente rispetto a una a carbone?", risposta: "Produce molta più energia, non emette CO₂ e ha un impatto minore sull'inquinamento atmosferico." },
        { domanda: "Quali sono i rischi principali legati all uso di una centrale elettronucleare?", risposta: "Possibili incidenti nucleari, gestione delle scorie radioattive e rischio di contaminazione." },
        { domanda: "Perché l'energia nucleare non produce emissioni di CO₂?", risposta: "Perché non brucia combustibili fossili, quindi non emette gas serra." },
        { domanda: "Quali paesi utilizzano maggiormente centrali elettronucleari ad acqua bollente?", risposta: "Stati Uniti, Giappone, Svezia e Germania." },
        { domanda: "Quali sono le alternative più sicure alle centrali elettronucleare ad acqua bollente?", risposta: "Reattori di nuova generazione, come i reattori a neutroni veloci o a fusione nucleare." },
        { domanda: "Quali eventi storici hanno influenzato lo sviluppo delle centrali elettronucleari?", risposta: "Incidenti come quelli di Chernobyl (1986) e Fukushima (2011) hanno portato a un maggiore controllo sulla sicurezza nucleare." },
        { domanda: "Quali potrebbero essere le evoluzioni future della tecnologia nucleare?", risposta: "L uso della fusione nucleare, reattori più sicuri e la riduzione delle scorie radioattive." }
    ]
};

function showQuestion(buttonNumber) {
    let selectedArray = domande[buttonNumber];

    if (!selectedArray) return;

    let randomIndex = Math.floor(Math.random() * selectedArray.length);
    let selectedQA = selectedArray[randomIndex];

    let questionText = document.getElementById("question-text");
    let answerText = document.getElementById("answer-text");
    let content = document.getElementById("content");

    questionText.innerText = `❓ ${selectedQA.domanda}`;
    answerText.innerText = `💡 ${selectedQA.risposta}`;

    content.classList.remove("hidden");

    answerText.style.display = 'none';

    questionText.addEventListener("click", function() {
        answerText.style.display = 'block';
    });
}
